add basket tag
miamtech/MealzNavModuleIOS pull request #46
Opened 2024-03-12 10:06 UTC by diarmuidmcg

2024-03-12 10:06 UTC, diarmuidmcg commented
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/miamtech/MealzNavModuleIOS/46?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#46** <a href="https://app.graphite.dev/github/pr/miamtech/MealzNavModuleIOS/46?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* **#45** <a href="https://app.graphite.dev/github/pr/miamtech/MealzNavModuleIOS/45?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#44** <a href="https://app.graphite.dev/github/pr/miamtech/MealzNavModuleIOS/44?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#43** <a href="https://app.graphite.dev/github/pr/miamtech/MealzNavModuleIOS/43?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @diarmuidmcg and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-03-21 09:25 UTC, diarmuidmcg commented on Sources/MealzNavModuleIOS/NavCoordinators/BasketTag/BasketTagFeatureConstructor.swift
> +import MiamIOSFramework
```suggestion
import MealzIOSFramework
```

2024-03-21 09:25 UTC, diarmuidmcg commented on Sources/MealzNavModuleIOS/NavCoordinators/BasketTag/BasketTagFeatureNavCoordinator.swift
> +import MiamIOSFramework
```suggestion
import mealzcore
import MealzIOSFramework
```

2024-03-21 09:25 UTC, diarmuidmcg commented on Sources/MealzNavModuleIOS/NavCoordinators/BasketTag/BasketTagFeatureNavCoordinatorProtocol.swift
> +import miamCore
```suggestion
import MealzIOSFramework
import mealzcore
```

2024-03-21 09:25 UTC, diarmuidmcg commented on Sources/MealzNavModuleIOS/NavCoordinators/BasketTag/MealzBasketTagFeatureSwiftUI.swift
> +import miamCore
```suggestion
import MealzUIModuleIOS
import mealzcore
```

2024-03-21 09:25 UTC, diarmuidmcg commented on Sources/MealzNavModuleIOS/NavCoordinators/BasketTag/MealzBasketTagFeatureUIKit.swift
> +import miamCore
```suggestion
import mealzcore
```

2024-03-21 09:25 UTC, diarmuidmcg commented on Sources/MealzNavModuleIOS/ViewController/GeneralViews/BasketTagViewController.swift
> +import miamCore
```suggestion
import MealzIOSFramework
import MealzUIModuleIOS
import mealzore
```

2024-03-21 09:26 UTC, diarmuidmcg commented on Sources/MealzNavModuleIOS/ViewController/GeneralViews/BasketTagViewController.swift
> +import mealzore
```suggestion
import mealzcore
```

2024-04-24 10:03 UTC, walerowicz-miam requested changes

2024-04-24 10:03 UTC, walerowicz-miam commented on Sources/MealzNavModuleIOS/NavCoordinators/BasketTag/MealzBasketTagFeatureSwiftUI.swift
> +        if let recipeCarpuselViewController = coordinator.navigationController.viewControllers.first {
recipeCarouselViewController

2024-04-24 12:18 UTC, diarmuidmcg commented on Sources/MealzNavModuleIOS/NavCoordinators/BasketTag/MealzBasketTagFeatureSwiftUI.swift
> +        if let recipeCarpuselViewController = coordinator.navigationController.viewControllers.first {
```suggestion
        if let recipeCarouselViewController = coordinator.navigationController.viewControllers.first {
```

2024-04-24 12:18 UTC, diarmuidmcg commented on Sources/MealzNavModuleIOS/NavCoordinators/BasketTag/MealzBasketTagFeatureSwiftUI.swift
> +            return recipeCarpuselViewController
```suggestion
            return recipeCarouselViewController
```

2024-04-24 12:19 UTC, diarmuidmcg commented on Sources/MealzNavModuleIOS/NavCoordinators/BasketTag/MealzBasketTagFeatureSwiftUI.swift
> +        if let recipeCarpuselViewController = coordinator.navigationController.viewControllers.first {
c'est fait

2024-04-24 13:13 UTC, merged